language: rust
rust:
  - stable
  - beta
  - nightly
jobs:
  allow_failures:
    - rust: nightly
  fast_finish: true
cache: cargo
script:
  - cargo build --verbose --all --release --features=cli
  - cargo test --verbose --all --release --features=cli
env:
  global:
    - RUST_BACKTRACE: full
git:
  depth: false
  quiet: true
after_success:
  cargo doc --document-private-items && \
    echo '<meta http-equiv=refresh content=0;url=ed_join/index.html>' > target/doc/index.html && \
    sudo pip install ghp-import && \
    ghp-import -n target/doc && \
    git push -qf https://${TOKEN}@github.com/${TRAVIS_REPO_SLUG}.git gh-pages
